version: '25.0.3'

services:
  php:
    image: php:8.2-apache
    container_name: php82
    ports:
      - 8000:80
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    build:
      context: .
      dockerfile: DockerFile

  db:
    image: mysql:8.0
    container_name: mysql8
    command: --default-authentication-plugin=caching_sha2_password --pid-file=/var/run/mysqld/mysqld.pid
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: securite
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - ./html/bdd:/docker-entrypoint-initdb.d

  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin    
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: pass
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgresql:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    depends_on:
      - db

  postgresql:
    image: postgres:13
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  portainer:
    image: portainer/portainer-ce
    ports:
      - 9001:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  portainer_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  
